- name: pre-reqs for community.docker
  hosts: localhost
  tags: prereqs
  tasks:
  - ansible.builtin.pip:
      name: requests

- name: create containers to use as ansible managed nodes
  hosts: localhost
  tasks:
  - containers.podman.podman_container:
      name: "{{ item }}"
      image: python
      tty: true
      interactive: true
    loop:
      - c1
      - c2
